#!/usr/bin/env python3
"""
YOLOv11 Training Example for Liquor Bottle Detection
Uses the dataset generated by product-capture-360-ts
"""

from ultralytics import YOLO
import os
from pathlib import Path

# Configuration
DATASET_PATH = "/path/to/yolo_dataset"  # Change this to your dataset path
MODEL_SIZE = "n"  # Options: n (nano), s (small), m (medium), l (large), x (xlarge)
EPOCHS = 100
BATCH_SIZE = 16
IMG_SIZE = 640
PROJECT_NAME = "liquor_bottle_detection"

# Training parameters
TRAIN_PARAMS = {
    "epochs": EPOCHS,
    "imgsz": IMG_SIZE,
    "batch": BATCH_SIZE,
    "name": PROJECT_NAME,
    "patience": 20,  # Early stopping patience
    "save": True,
    "save_period": 10,  # Save checkpoint every 10 epochs
    "cache": False,  # Set to True if dataset fits in RAM
    "device": 0,  # 0 for GPU, 'cpu' for CPU
    "workers": 8,
    "optimizer": "AdamW",
    "lr0": 0.01,  # Initial learning rate
    "lrf": 0.01,  # Final learning rate (lr0 * lrf)
    "momentum": 0.937,
    "weight_decay": 0.0005,
    "warmup_epochs": 3.0,
    "warmup_momentum": 0.8,
    "warmup_bias_lr": 0.1,
    "augment": True,
    "mosaic": 1.0,
    "mixup": 0.1,
    "copy_paste": 0.1,
    "degrees": 0.0,  # Already augmented in preprocessing
    "translate": 0.1,
    "scale": 0.5,
    "shear": 0.0,
    "perspective": 0.0,
    "flipud": 0.0,
    "fliplr": 0.5,
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.4,
}

def create_data_yaml():
    """Create data.yaml configuration file"""
    yaml_path = Path(DATASET_PATH) / "data.yaml"

    yaml_content = f"""# YOLOv11 Dataset Configuration
# Generated by product-capture-360-ts

path: {DATASET_PATH}
train: images  # Path to training images
val: images    # Path to validation images (split your data appropriately)

# Classes
nc: 1  # number of classes
names: ['liquor_bottle']  # class names

# Optional: class weights for imbalanced datasets
# class_weights: [1.0]
"""

    with open(yaml_path, 'w') as f:
        f.write(yaml_content)

    print(f"✅ Created data.yaml at {yaml_path}")
    return yaml_path

def train_model():
    """Train YOLOv11 model"""
    print("🚀 Starting YOLOv11 Training Pipeline")
    print("=" * 60)

    # Verify dataset exists
    if not os.path.exists(DATASET_PATH):
        print(f"❌ Error: Dataset path not found: {DATASET_PATH}")
        print("Please update DATASET_PATH in this script")
        return

    images_dir = Path(DATASET_PATH) / "images"
    if not images_dir.exists():
        print(f"❌ Error: Images directory not found: {images_dir}")
        return

    image_count = len(list(images_dir.glob("*.jpg")))
    print(f"📊 Found {image_count} images in dataset")

    if image_count < 100:
        print("⚠️  Warning: Dataset is small (<100 images). Results may be poor.")
        print("   Consider capturing more angles or using more backgrounds.")

    # Create data.yaml
    data_yaml = create_data_yaml()

    # Load model
    print(f"\n📦 Loading YOLOv11{MODEL_SIZE} model...")
    model = YOLO(f'yolov11{MODEL_SIZE}.pt')

    # Display model info
    print(f"\n📋 Model: YOLOv11{MODEL_SIZE}")
    print(f"📋 Dataset: {DATASET_PATH}")
    print(f"📋 Epochs: {EPOCHS}")
    print(f"📋 Batch size: {BATCH_SIZE}")
    print(f"📋 Image size: {IMG_SIZE}")
    print(f"📋 Device: {'GPU' if TRAIN_PARAMS['device'] == 0 else 'CPU'}")

    # Train
    print("\n🎓 Starting training...")
    print("=" * 60)

    results = model.train(
        data=str(data_yaml),
        **TRAIN_PARAMS
    )

    print("\n✅ Training complete!")
    print("=" * 60)

    # Validate
    print("\n📊 Running validation...")
    metrics = model.val()

    print(f"\n📈 Final Metrics:")
    print(f"   mAP@50: {metrics.box.map50:.4f}")
    print(f"   mAP@50-95: {metrics.box.map:.4f}")
    print(f"   Precision: {metrics.box.mp:.4f}")
    print(f"   Recall: {metrics.box.mr:.4f}")

    # Export model
    print("\n📦 Exporting model...")
    export_path = model.export(format='onnx')
    print(f"✅ ONNX model exported to: {export_path}")

    print("\n🎉 All done!")
    print(f"   Best weights: runs/{PROJECT_NAME}/weights/best.pt")
    print(f"   Last weights: runs/{PROJECT_NAME}/weights/last.pt")
    print(f"\n💡 Test your model:")
    print(f"   from ultralytics import YOLO")
    print(f"   model = YOLO('runs/{PROJECT_NAME}/weights/best.pt')")
    print(f"   results = model.predict('path/to/test/image.jpg')")

def predict_example():
    """Example of using trained model for inference"""
    print("\n🔮 Inference Example:")
    print("-" * 60)
    print("""
from ultralytics import YOLO
import cv2

# Load your trained model
model = YOLO('runs/liquor_bottle_detection/weights/best.pt')

# Predict on new images
results = model.predict(
    source='path/to/test/image.jpg',
    conf=0.25,  # Confidence threshold
    iou=0.45,   # NMS IoU threshold
    save=True,  # Save results
    show=True   # Display results
)

# Process results
for result in results:
    boxes = result.boxes  # Bounding boxes
    for box in boxes:
        x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
        confidence = box.conf[0].cpu().numpy()
        class_id = int(box.cls[0].cpu().numpy())

        print(f"Detected: liquor_bottle at ({x1:.0f}, {y1:.0f}, {x2:.0f}, {y2:.0f})")
        print(f"Confidence: {confidence:.2%}")

# Export to different formats
model.export(format='onnx')      # ONNX
model.export(format='torchscript')  # TorchScript
model.export(format='coreml')    # CoreML (for iOS)
model.export(format='tflite')    # TensorFlow Lite
    """)

if __name__ == "__main__":
    try:
        # Check if ultralytics is installed
        import ultralytics
        print(f"✅ Ultralytics YOLO version: {ultralytics.__version__}")
    except ImportError:
        print("❌ Error: ultralytics not installed")
        print("   Install with: pip install ultralytics")
        exit(1)

    # Check CUDA availability
    import torch
    if torch.cuda.is_available():
        print(f"✅ CUDA available: {torch.cuda.get_device_name(0)}")
        print(f"   CUDA version: {torch.version.cuda}")
    else:
        print("⚠️  CUDA not available. Training will use CPU (slower)")
        TRAIN_PARAMS['device'] = 'cpu'

    print("\n" + "=" * 60)
    input("Press Enter to start training (Ctrl+C to cancel)...")
    print()

    train_model()
    predict_example()
